### ISSUE TITLE
GriefPrevention defaults do not work

### ISSUE THREAD

**Issue by bloodmc** [djxy/PermissionManager-2.0#10]
As I stated on Sponge's forums, PermissionManager has not properly implemented the default subject.

https://github.com/djxy/PermissionManager-2.0/blob/master/src/main/java/io/github/djxy/permissionmanager/subjects/special/Special.java

Special seems to be the default subject and as you can see, it is just a placeholder that has no logic and returns TRUE for all permission checks.

Transient subject data is also ignored as shown here

https://github.com/djxy/PermissionManager-2.0/blob/master/src/main/java/io/github/djxy/permissionmanager/subjects/Subject.java#L86

getSubjectData and getTransientSubjectData should NOT be returning the same data...Transient is meant to never persist so this needs to be fixed.

Once the above issues are resolved, I'll retest GP but as it stands now there is no way it will work.

**Comment by djxy** [comment]
I changed the default subject, it was the default group, because some plugins/mods were setting their permissions on it and it was a problem for some people.

Also, I'm not sure to understand the difference between getSubjectData and getTransientSubjectData. That's why they return the same thing.

**Comment by bloodmc** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/service/permission/PermissionService.java#L63

Your current implementation of getDefaults does not follow the contract set forth by our API. If users had issues with it then they weren't handling their permissions properly as defaults are meant to be the LOWEST priority of all subjects. Simply ignoring it as you do now breaks any plugin that attempts to use getDefaults.

As for transient data, the javadocs explain it clearly

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/service/permission/Subject.java#L94

If you need help implementing this properly, check PermissionsEx.

**Comment by djxy** [comment]
https://github.com/djxy/PermissionManager-2.0/commit/a71d7ae8d3acf4a88361cf6c5b206892f3ada6ea

This is the commit to support the default subject. The default subject is only stored in the memory currently. I will change the getTransientSubjectData to only be stored in memory and the getSubjectData stored on a file.

**Comment by bloodmc** [comment]
@djxy OK let me know when you fix transient data then I'll test it.

**Comment by djxy** [comment]
I fixed the transient data. I tested with branch GriefPrevention-Support and GriefPrevention cancelled the event when I tried to break a block. After that, I tested with the version 2.4.0 and GriefPrevention wasn't working with it.

**Comment by bloodmc** [comment]
@djxy OK i'll test in a few and let you know how it turns out.

Thanks!

**Comment by bloodmc** [comment]
@djxy I'm unable to build PM due to missing dependencies. Can you provide a jar?

Thanks!

**Comment by djxy** [comment]
Yes, but wath are the jars that you need? If you clone my project you have a folder with the jars inside. It called libs.

**Comment by djxy** [comment]
If you really need à jar, I will created one in two jours.

**Comment by bloodmc** [comment]
@djxy Ah didn't realize that, OK i'll build it myself. Thanks

**Comment by bloodmc** [comment]
@djxy I just built latest source and was not able to use any commands. When I checked the config folder, I saw a permissionmanager folder with 3 subfolders (groups, promotions, users) which had no files.

**Comment by djxy** [comment]
Yes, to use a command you have to use the console. The folder are empty because there is no group, player and promotion. If you want to use a command you can give you all the permissions /pm users blood set permission *

**Comment by djxy** [comment]
Does it work?

**Comment by bloodmc** [comment]
@djxy Testing now.

**Comment by bloodmc** [comment]
@djxy 
[14:05:47] [Server thread/INFO] [nucleus/]: KratosKnox2 ran the command: /gamemode 1
[14:05:47] [Server thread/INFO] [io.github.djxy.permissionmanager.subjects.group.Group/]: Subject: default-39e091 - Contexts [world=world] - Permission: nucleus.gamemode.base - Tristate: UNDEFINED

LuckPerms and PEX both support wildcard perms by not including '*'. Can you add support for this in PM?

**Comment by bloodmc** [comment]
Default permission do not seem to be working. I created a claim and set the block-break flag to true, logged in with a second user and attempted to break a block but failed.

**Comment by djxy** [comment]
Did you build the branch GriefPrevention-Support?

**Comment by bloodmc** [comment]
@djxy Let me make sure I built the right branch.

**Comment by bloodmc** [comment]
Yes i'm using the GriefPrevention-Support branch.

**Comment by djxy** [comment]
I updated the default class, you can pull.

**Comment by djxy** [comment]
Wait!!

**Comment by djxy** [comment]
It's good now. I fixed a mistake that I made with the Default. It was always returning UNDEFINED for the permissions.

**Comment by bloodmc** [comment]
@djxy OK let me test.

**Comment by bloodmc** [comment]
@djxy When I change a default flag in a claim, I get spammed with this now

https://gist.github.com/bloodmc/f51b3ca0ec8abef131f3adf85ae17ba6

**Comment by bloodmc** [comment]
It might be better if you just test GP on your end. Grab the plugin from
http://files.minecraftforge.net/maven/me/ryanhamshire/griefprevention/1.10.2-2.1.0.85/griefprevention-1.10.2-2.1.0.85.jar

**Comment by djxy** [comment]
I fixed the bug.

**Comment by bloodmc** [comment]
@djxy OK I'll try again.

**Comment by bloodmc** [comment]
@djxy Default permissions still do not work. The default file generated in "groups" folder only has

default: true

If I set a permission via command on the default user, it should be persisting to file.

**Comment by djxy** [comment]
It persists, I have set the permission * to my user and everything was fine. It was in the file when I saved it.

**Comment by djxy** [comment]
Did you save the group?

**Comment by bloodmc** [comment]
@djxy I'm going to wipe all files and let them regen

**Comment by djxy** [comment]
I tested and everything was fine. The default subject is saved and loaded when the server stop and start.

**Comment by bloodmc** [comment]
@djxy I'll check again when I get home.

**Comment by djxy** [comment]
It now supports the permissions like you asked. `nucleus` == `nucleus.*`

**Comment by bloodmc** [comment]
@djxy Tested latest build, defaults seem to be working now =) and the wildcard permission without '*' seems to work. I see the defaults only persist when stopping the server and not during a world save. You should use the following event to save PM permissions during world saves

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/world/SaveWorldEvent.java#L39

Supporting this would mean every world save, PM settings would be saved which is what a user expects. Also maybe a '/pm save' command to force a save for PM only?

The reason the above is important is a server can crash or a user can force close the server without running /stop etc.. Once the above is resolved, I'll test further. Thanks!

**Comment by djxy** [comment]
Currently, you can save and load à group/user at anytime. I will support the event when the World save.

**Comment by bloodmc** [comment]
@djxy What if I change multiple groups/users on file directly, is there a command that lets me reload it all?

**Comment by djxy** [comment]
In the branch you have you can't can't reload all the groups, but v2.4.0 can reload all the groups. I don't want to reload all the players because they are not all online. I could reload only the players online.

**Comment by djxy** [comment]
The users, groups, promotions and the default subject are now saved when a world is saved. I will add a command to reload the players online.

**Comment by bloodmc** [comment]
Change your SaveWorldEvent listener to SaveWorldEvent.Post or it will save twice.

**Comment by djxy** [comment]
Done, changed the event to SaveWorldEvent.Post and added the command to load the online users. `/pm load users`

**Comment by bloodmc** [comment]
@djxy doing a /save-all seems to wipe the data now. My default file just had the word "null" in it.

**Comment by djxy** [comment]
Only the default subject or every subject?

**Comment by bloodmc** [comment]
@djxy seems like only the default subject.

**Comment by djxy** [comment]
The file is null If there is no permissions, options, groups or any other data. What was inside?

**Comment by bloodmc** [comment]
@djxy Ah my mistake, I didn't realize I removed my default override. Just tested again and it's working as expected =)

**Comment by djxy** [comment]
Good. So PM is working with GriefPrevention?

**Comment by bloodmc** [comment]
@djxy So far but still testing. How do I set an option on a player?

**Comment by djxy** [comment]
/pm users user set option option value

**Comment by bloodmc** [comment]
Found a bug

I have a default flag permission "griefprevention.claim.flag.block-break" set to false as transient. If I add the default permission "griefprevention.claim.flag.block-break.minecraft.chest" and attempt to place a chest, it gets denied. So it seems the inheritance checks are bugged as the checks should be as follows 

1. griefprevention.claim.flag.block-break.minecraft.chest  allowed ? if YES return else go to step 2
2. griefprevention.claim.flag.block-break.minecraft           allowed ? if YES return else go to step 3
3. griefprevention.claim.flag.block-break                           allowed ? if YES return else go to step 4
etc.

**Comment by bloodmc** [comment]
I updated it, I believe this is how PEX does it but I need to confirm

**Comment by djxy** [comment]
I think I fixed it, but I'm not sure to understand how you set your permissions.

**Comment by bloodmc** [comment]
@djxy OK it still doesn't work, let me explain again

Player A places down a chest and GP requests the value for the following permission "griefprevention.claim.flag.block-break.minecraft.chest"

PEX would do the following in order at the highest level subject (group/user)

1. Does permission "griefprevention.claim.flag.block-break.minecraft.chest" exist? If so, return the value. If not, proceed to step 2.
2. Does permission "griefprevention.claim.flag.block-break.minecraft" exist? If so, return the value. If not proceed to step 3.
3. Does permission "griefprevention.claim.flag.block-break" exist? If so return the value, if not proceed to step 4.
4. Does permission "griefprevention.claim.flag" exist ? If so return the value. If not, proceed to step 5.
5. Does permission "griefprevention.claim" exist? If so return the value. If not, proceed to final step.
6. Does permission "griefprevention" exist? If so return the value. If not, check parent subject and repeat.

**Comment by bloodmc** [comment]
@djxy Please join webchat.esper.net and join #sponge-perms

**Comment by djxy** [comment]
@bloodmc I fixed the permission verification system like we said on the irc. The order now, User transient data, User persistent data, Group transient data, Group persistent data, Default persistent data and Default transient data.
